"""add 8 new data tables phase49

Revision ID: 40ed3b843e8d
Revises: 2a146f5a0630
Create Date: 2026-04-01 23:34:27.762170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '40ed3b843e8d'
down_revision: Union[str, Sequence[str], None] = '2a146f5a0630'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hk_hold',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=16), nullable=True),
    sa.Column('trade_date', sa.String(length=8), nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('vol', sa.Float(), nullable=True),
    sa.Column('ratio', sa.Float(), nullable=True),
    sa.Column('exchange', sa.String(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', 'ts_code', 'exchange', name='uq_hk_hold_date_code_exch')
    )
    op.create_index(op.f('ix_hk_hold_trade_date'), 'hk_hold', ['trade_date'], unique=False)
    op.create_index(op.f('ix_hk_hold_ts_code'), 'hk_hold', ['ts_code'], unique=False)
    op.create_table('index_dailybasic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False),
    sa.Column('total_mv', sa.Float(), nullable=True),
    sa.Column('float_mv', sa.Float(), nullable=True),
    sa.Column('total_share', sa.Float(), nullable=True),
    sa.Column('float_share', sa.Float(), nullable=True),
    sa.Column('free_share', sa.Float(), nullable=True),
    sa.Column('turnover_rate', sa.Float(), nullable=True),
    sa.Column('turnover_rate_f', sa.Float(), nullable=True),
    sa.Column('pe', sa.Float(), nullable=True),
    sa.Column('pe_ttm', sa.Float(), nullable=True),
    sa.Column('pb', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'trade_date', name='uq_idx_dailybasic')
    )
    op.create_index(op.f('ix_index_dailybasic_trade_date'), 'index_dailybasic', ['trade_date'], unique=False)
    op.create_index(op.f('ix_index_dailybasic_ts_code'), 'index_dailybasic', ['ts_code'], unique=False)
    op.create_table('margin',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False),
    sa.Column('exchange_id', sa.String(length=8), nullable=True),
    sa.Column('rzye', sa.Float(), nullable=True),
    sa.Column('rzmre', sa.Float(), nullable=True),
    sa.Column('rzche', sa.Float(), nullable=True),
    sa.Column('rqye', sa.Float(), nullable=True),
    sa.Column('rqmcl', sa.Float(), nullable=True),
    sa.Column('rzrqye', sa.Float(), nullable=True),
    sa.Column('rqyl', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', 'exchange_id', name='uq_margin_date_exch')
    )
    op.create_index(op.f('ix_margin_trade_date'), 'margin', ['trade_date'], unique=False)
    op.create_table('share_float',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('ann_date', sa.String(length=8), nullable=True),
    sa.Column('float_date', sa.String(length=8), nullable=True),
    sa.Column('float_share', sa.Float(), nullable=True),
    sa.Column('float_ratio', sa.Float(), nullable=True),
    sa.Column('holder_name', sa.String(length=200), nullable=True),
    sa.Column('share_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'float_date', 'holder_name', 'share_type', name='uq_share_float')
    )
    op.create_index(op.f('ix_share_float_float_date'), 'share_float', ['float_date'], unique=False)
    op.create_index(op.f('ix_share_float_ts_code'), 'share_float', ['ts_code'], unique=False)
    op.create_table('stk_holdernumber',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('ann_date', sa.String(length=8), nullable=True),
    sa.Column('end_date', sa.String(length=8), nullable=True),
    sa.Column('holder_num', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'end_date', 'ann_date', name='uq_stk_holdernumber')
    )
    op.create_index(op.f('ix_stk_holdernumber_end_date'), 'stk_holdernumber', ['end_date'], unique=False)
    op.create_index(op.f('ix_stk_holdernumber_ts_code'), 'stk_holdernumber', ['ts_code'], unique=False)
    op.create_table('stk_holdertrade',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('ann_date', sa.String(length=8), nullable=True),
    sa.Column('holder_name', sa.String(length=200), nullable=True),
    sa.Column('holder_type', sa.String(length=4), nullable=True),
    sa.Column('in_de', sa.String(length=8), nullable=True),
    sa.Column('change_vol', sa.Float(), nullable=True),
    sa.Column('change_ratio', sa.Float(), nullable=True),
    sa.Column('after_share', sa.Float(), nullable=True),
    sa.Column('after_ratio', sa.Float(), nullable=True),
    sa.Column('avg_price', sa.Float(), nullable=True),
    sa.Column('total_share', sa.Float(), nullable=True),
    sa.Column('begin_date', sa.String(length=8), nullable=True),
    sa.Column('close_date', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'ann_date', 'holder_name', 'in_de', 'change_vol', name='uq_stk_holdertrade')
    )
    op.create_index(op.f('ix_stk_holdertrade_ann_date'), 'stk_holdertrade', ['ann_date'], unique=False)
    op.create_index(op.f('ix_stk_holdertrade_ts_code'), 'stk_holdertrade', ['ts_code'], unique=False)
    op.create_table('top10_floatholders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('ann_date', sa.String(length=8), nullable=True),
    sa.Column('end_date', sa.String(length=8), nullable=True),
    sa.Column('holder_name', sa.String(length=200), nullable=True),
    sa.Column('hold_amount', sa.Float(), nullable=True),
    sa.Column('hold_ratio', sa.Float(), nullable=True),
    sa.Column('hold_float_ratio', sa.Float(), nullable=True),
    sa.Column('hold_change', sa.Float(), nullable=True),
    sa.Column('holder_type', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'end_date', 'holder_name', name='uq_top10_float')
    )
    op.create_index(op.f('ix_top10_floatholders_end_date'), 'top10_floatholders', ['end_date'], unique=False)
    op.create_index(op.f('ix_top10_floatholders_ts_code'), 'top10_floatholders', ['ts_code'], unique=False)
    op.create_table('top_inst',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=True),
    sa.Column('exalter', sa.String(length=128), nullable=True),
    sa.Column('side', sa.String(length=8), nullable=True),
    sa.Column('buy', sa.Float(), nullable=True),
    sa.Column('buy_rate', sa.Float(), nullable=True),
    sa.Column('sell', sa.Float(), nullable=True),
    sa.Column('sell_rate', sa.Float(), nullable=True),
    sa.Column('net_buy', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', 'ts_code', 'exalter', 'side', name='uq_top_inst')
    )
    op.create_index(op.f('ix_top_inst_trade_date'), 'top_inst', ['trade_date'], unique=False)
    op.create_index(op.f('ix_top_inst_ts_code'), 'top_inst', ['ts_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('top_inst')
    op.drop_table('top10_floatholders')
    op.drop_table('stk_holdertrade')
    op.drop_table('stk_holdernumber')
    op.drop_table('share_float')
    op.drop_table('margin')
    op.drop_table('index_dailybasic')
    op.drop_table('hk_hold')
