"""add fina and sentiment tables

Revision ID: 9c43c6c8212d
Revises: 3216d25c234b
Create Date: 2026-03-29 23:50:48.869296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c43c6c8212d'
down_revision: Union[str, Sequence[str], None] = '3216d25c234b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dc_hot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False),
    sa.Column('data_type', sa.String(length=32), nullable=True),
    sa.Column('ts_code', sa.String(length=16), nullable=True),
    sa.Column('ts_name', sa.String(length=32), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('pct_change', sa.Float(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', 'ts_code', 'data_type', name='uq_dc_hot_dtcdt')
    )
    op.create_index(op.f('ix_dc_hot_trade_date'), 'dc_hot', ['trade_date'], unique=False)
    op.create_index(op.f('ix_dc_hot_ts_code'), 'dc_hot', ['ts_code'], unique=False)
    op.create_table('disclosure_date',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('ann_date', sa.String(length=8), nullable=True),
    sa.Column('end_date', sa.String(length=8), nullable=False),
    sa.Column('pre_date', sa.String(length=8), nullable=True),
    sa.Column('actual_date', sa.String(length=8), nullable=True),
    sa.Column('modify_date', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'end_date', name='uq_disclosure_date_code_end')
    )
    op.create_index(op.f('ix_disclosure_date_end_date'), 'disclosure_date', ['end_date'], unique=False)
    op.create_index(op.f('ix_disclosure_date_ts_code'), 'disclosure_date', ['ts_code'], unique=False)
    op.create_table('fina_indicator',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('ann_date', sa.String(length=8), nullable=True),
    sa.Column('end_date', sa.String(length=8), nullable=False),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('dt_eps', sa.Float(), nullable=True),
    sa.Column('profit_dedt', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('roe_waa', sa.Float(), nullable=True),
    sa.Column('roe_dt', sa.Float(), nullable=True),
    sa.Column('roa', sa.Float(), nullable=True),
    sa.Column('netprofit_margin', sa.Float(), nullable=True),
    sa.Column('grossprofit_margin', sa.Float(), nullable=True),
    sa.Column('debt_to_assets', sa.Float(), nullable=True),
    sa.Column('ocfps', sa.Float(), nullable=True),
    sa.Column('bps', sa.Float(), nullable=True),
    sa.Column('current_ratio', sa.Float(), nullable=True),
    sa.Column('quick_ratio', sa.Float(), nullable=True),
    sa.Column('netprofit_yoy', sa.Float(), nullable=True),
    sa.Column('dt_netprofit_yoy', sa.Float(), nullable=True),
    sa.Column('tr_yoy', sa.Float(), nullable=True),
    sa.Column('or_yoy', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'end_date', name='uq_fina_indicator_code_end')
    )
    op.create_index(op.f('ix_fina_indicator_end_date'), 'fina_indicator', ['end_date'], unique=False)
    op.create_index(op.f('ix_fina_indicator_ts_code'), 'fina_indicator', ['ts_code'], unique=False)
    op.create_table('fina_mainbz',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('end_date', sa.String(length=8), nullable=False),
    sa.Column('bz_item', sa.String(length=128), nullable=True),
    sa.Column('bz_sales', sa.Float(), nullable=True),
    sa.Column('bz_profit', sa.Float(), nullable=True),
    sa.Column('bz_cost', sa.Float(), nullable=True),
    sa.Column('curr_type', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'end_date', 'bz_item', name='uq_fina_mainbz_code_end_item')
    )
    op.create_index(op.f('ix_fina_mainbz_end_date'), 'fina_mainbz', ['end_date'], unique=False)
    op.create_index(op.f('ix_fina_mainbz_ts_code'), 'fina_mainbz', ['ts_code'], unique=False)
    op.create_table('forecast',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('ann_date', sa.String(length=8), nullable=True),
    sa.Column('end_date', sa.String(length=8), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=True),
    sa.Column('p_change_min', sa.Float(), nullable=True),
    sa.Column('p_change_max', sa.Float(), nullable=True),
    sa.Column('net_profit_min', sa.Float(), nullable=True),
    sa.Column('net_profit_max', sa.Float(), nullable=True),
    sa.Column('last_parent_net', sa.Float(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'ann_date', 'end_date', name='uq_forecast_code_ann_end')
    )
    op.create_index(op.f('ix_forecast_ann_date'), 'forecast', ['ann_date'], unique=False)
    op.create_index(op.f('ix_forecast_ts_code'), 'forecast', ['ts_code'], unique=False)
    op.create_table('hm_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('ts_name', sa.String(length=32), nullable=True),
    sa.Column('buy_amount', sa.Float(), nullable=True),
    sa.Column('sell_amount', sa.Float(), nullable=True),
    sa.Column('net_amount', sa.Float(), nullable=True),
    sa.Column('hm_name', sa.String(length=64), nullable=True),
    sa.Column('tag', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', 'ts_code', 'hm_name', name='uq_hm_detail_dtcn')
    )
    op.create_index(op.f('ix_hm_detail_trade_date'), 'hm_detail', ['trade_date'], unique=False)
    op.create_index(op.f('ix_hm_detail_ts_code'), 'hm_detail', ['ts_code'], unique=False)
    op.create_table('income',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('ann_date', sa.String(length=8), nullable=True),
    sa.Column('f_ann_date', sa.String(length=8), nullable=True),
    sa.Column('end_date', sa.String(length=8), nullable=False),
    sa.Column('report_type', sa.String(length=4), nullable=True),
    sa.Column('total_revenue', sa.Float(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('oper_cost', sa.Float(), nullable=True),
    sa.Column('sell_exp', sa.Float(), nullable=True),
    sa.Column('admin_exp', sa.Float(), nullable=True),
    sa.Column('fin_exp', sa.Float(), nullable=True),
    sa.Column('rd_exp', sa.Float(), nullable=True),
    sa.Column('operate_profit', sa.Float(), nullable=True),
    sa.Column('total_profit', sa.Float(), nullable=True),
    sa.Column('income_tax', sa.Float(), nullable=True),
    sa.Column('n_income', sa.Float(), nullable=True),
    sa.Column('n_income_attr_p', sa.Float(), nullable=True),
    sa.Column('basic_eps', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'end_date', 'report_type', name='uq_income_code_end_rpt')
    )
    op.create_index(op.f('ix_income_end_date'), 'income', ['end_date'], unique=False)
    op.create_index(op.f('ix_income_ts_code'), 'income', ['ts_code'], unique=False)
    op.create_table('limit_cpt_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('days', sa.Integer(), nullable=True),
    sa.Column('up_stat', sa.String(length=32), nullable=True),
    sa.Column('cons_nums', sa.Integer(), nullable=True),
    sa.Column('up_nums', sa.Integer(), nullable=True),
    sa.Column('pct_chg', sa.Float(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', 'ts_code', name='uq_limit_cpt_list_dtc')
    )
    op.create_index(op.f('ix_limit_cpt_list_trade_date'), 'limit_cpt_list', ['trade_date'], unique=False)
    op.create_table('limit_list_ths',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('pct_chg', sa.Float(), nullable=True),
    sa.Column('limit_type', sa.String(length=16), nullable=True),
    sa.Column('first_lu_time', sa.String(length=16), nullable=True),
    sa.Column('last_lu_time', sa.String(length=16), nullable=True),
    sa.Column('open_num', sa.Integer(), nullable=True),
    sa.Column('limit_amount', sa.Float(), nullable=True),
    sa.Column('turnover_rate', sa.Float(), nullable=True),
    sa.Column('tag', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', 'ts_code', 'limit_type', name='uq_limit_list_ths_dtcl')
    )
    op.create_index(op.f('ix_limit_list_ths_trade_date'), 'limit_list_ths', ['trade_date'], unique=False)
    op.create_index(op.f('ix_limit_list_ths_ts_code'), 'limit_list_ths', ['ts_code'], unique=False)
    op.create_table('limit_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('industry', sa.String(length=32), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('pct_chg', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('limit_amount', sa.Float(), nullable=True),
    sa.Column('float_mv', sa.Float(), nullable=True),
    sa.Column('first_time', sa.String(length=16), nullable=True),
    sa.Column('last_time', sa.String(length=16), nullable=True),
    sa.Column('open_times', sa.Integer(), nullable=True),
    sa.Column('limit_times', sa.Integer(), nullable=True),
    sa.Column('limit', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', 'ts_code', 'limit', name='uq_limit_stats_dtcl')
    )
    op.create_index(op.f('ix_limit_stats_trade_date'), 'limit_stats', ['trade_date'], unique=False)
    op.create_index(op.f('ix_limit_stats_ts_code'), 'limit_stats', ['ts_code'], unique=False)
    op.create_table('limit_step',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('nums', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', 'ts_code', name='uq_limit_step_dtc')
    )
    op.create_index(op.f('ix_limit_step_trade_date'), 'limit_step', ['trade_date'], unique=False)
    op.create_index(op.f('ix_limit_step_ts_code'), 'limit_step', ['ts_code'], unique=False)
    op.create_table('top_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('pct_change', sa.Float(), nullable=True),
    sa.Column('turnover_rate', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('l_sell', sa.Float(), nullable=True),
    sa.Column('l_buy', sa.Float(), nullable=True),
    sa.Column('l_amount', sa.Float(), nullable=True),
    sa.Column('net_amount', sa.Float(), nullable=True),
    sa.Column('net_rate', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', 'ts_code', name='uq_top_list_dtc')
    )
    op.create_index(op.f('ix_top_list_trade_date'), 'top_list', ['trade_date'], unique=False)
    op.create_index(op.f('ix_top_list_ts_code'), 'top_list', ['ts_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    tables = [
        'top_list', 'limit_step', 'limit_stats', 'limit_list_ths',
        'limit_cpt_list', 'income', 'hm_detail', 'forecast',
        'fina_mainbz', 'fina_indicator', 'disclosure_date', 'dc_hot',
    ]
    for t in tables:
        op.drop_table(t)
    # REMOVED: partition table recreation and manual index drops
