"""add sim_orders sim_trades sim_positions sim_account audit_log

Revision ID: a008f95a8b9a
Revises: c9d7017b3e92
Create Date: 2026-03-22 17:53:49.466940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a008f95a8b9a'
down_revision: Union[str, Sequence[str], None] = 'c9d7017b3e92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('event_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_timestamp'), 'audit_log', ['timestamp'], unique=False)
    op.create_table('sim_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_asset', sa.Float(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('frozen', sa.Float(), nullable=False),
    sa.Column('market_value', sa.Float(), nullable=False),
    sa.Column('total_pnl', sa.Float(), nullable=False),
    sa.Column('today_pnl', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sim_orders',
    sa.Column('order_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('signal_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('order_type', sa.String(length=8), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('filled_qty', sa.Integer(), nullable=False),
    sa.Column('filled_price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('slippage', sa.Float(), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_sim_orders_signal_id'), 'sim_orders', ['signal_id'], unique=False)
    op.create_index(op.f('ix_sim_orders_status'), 'sim_orders', ['status'], unique=False)
    op.create_index(op.f('ix_sim_orders_ts_code'), 'sim_orders', ['ts_code'], unique=False)
    op.create_table('sim_positions',
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('avg_cost', sa.Float(), nullable=False),
    sa.Column('market_price', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('realized_pnl', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('ts_code')
    )
    op.create_table('sim_trades',
    sa.Column('trade_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('order_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('side', sa.String(length=4), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('slippage', sa.Float(), nullable=False),
    sa.Column('traded_at', sa.DateTime(), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('trade_id')
    )
    op.create_index(op.f('ix_sim_trades_order_id'), 'sim_trades', ['order_id'], unique=False)
    op.create_index(op.f('ix_sim_trades_ts_code'), 'sim_trades', ['ts_code'], unique=False)
    # NOTE: stock_min_kline partition sub-tables are managed by raw SQL,
    # NOT by Alembic. Autogenerate false-positives removed here.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: partition sub-table recreation removed (managed by raw SQL)
    op.drop_index(op.f('ix_sim_trades_ts_code'), table_name='sim_trades')
    op.drop_index(op.f('ix_sim_trades_order_id'), table_name='sim_trades')
    op.drop_table('sim_trades')
    op.drop_table('sim_positions')
    op.drop_index(op.f('ix_sim_orders_ts_code'), table_name='sim_orders')
    op.drop_index(op.f('ix_sim_orders_status'), table_name='sim_orders')
    op.drop_index(op.f('ix_sim_orders_signal_id'), table_name='sim_orders')
    op.drop_table('sim_orders')
    op.drop_table('sim_account')
    op.drop_index(op.f('ix_audit_log_timestamp'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
