"""add daily_basic index_basic index_daily index_classify

Revision ID: c9d7017b3e92
Revises: e73cfd70b079
Create Date: 2026-03-22 03:00:42.110004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9d7017b3e92'
down_revision: Union[str, Sequence[str], None] = 'e73cfd70b079'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_basic',
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('turnover_rate', sa.Float(), nullable=True),
    sa.Column('turnover_rate_f', sa.Float(), nullable=True),
    sa.Column('volume_ratio', sa.Float(), nullable=True),
    sa.Column('pe', sa.Float(), nullable=True),
    sa.Column('pe_ttm', sa.Float(), nullable=True),
    sa.Column('pb', sa.Float(), nullable=True),
    sa.Column('ps', sa.Float(), nullable=True),
    sa.Column('ps_ttm', sa.Float(), nullable=True),
    sa.Column('dv_ratio', sa.Float(), nullable=True),
    sa.Column('dv_ttm', sa.Float(), nullable=True),
    sa.Column('total_share', sa.Float(), nullable=True),
    sa.Column('float_share', sa.Float(), nullable=True),
    sa.Column('free_share', sa.Float(), nullable=True),
    sa.Column('total_mv', sa.Float(), nullable=True),
    sa.Column('circ_mv', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('ts_code', 'trade_date')
    )
    op.create_table('index_basic',
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('fullname', sa.String(length=128), nullable=True),
    sa.Column('market', sa.String(length=16), nullable=True),
    sa.Column('publisher', sa.String(length=32), nullable=True),
    sa.Column('index_type', sa.String(length=32), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('base_date', sa.String(length=8), nullable=True),
    sa.Column('base_point', sa.Float(), nullable=True),
    sa.Column('list_date', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('ts_code')
    )
    op.create_table('index_classify',
    sa.Column('index_code', sa.String(length=16), nullable=False),
    sa.Column('industry_name', sa.String(length=32), nullable=True),
    sa.Column('parent_code', sa.String(length=16), nullable=True),
    sa.Column('level', sa.String(length=4), nullable=True),
    sa.Column('industry_code', sa.String(length=16), nullable=True),
    sa.Column('is_pub', sa.String(length=1), nullable=True),
    sa.Column('src', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('index_code')
    )
    op.create_table('index_daily',
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('pre_close', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('pct_chg', sa.Float(), nullable=True),
    sa.Column('vol', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('ts_code', 'trade_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('index_daily')
    op.drop_table('index_classify')
    op.drop_table('index_basic')
    op.drop_table('daily_basic')
    # ### end Alembic commands ###
