"""init stock_basic trade_cal stock_daily

Revision ID: e73cfd70b079
Revises: 
Create Date: 2026-03-21 23:54:23.122398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e73cfd70b079'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_basic',
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('area', sa.String(length=16), nullable=True),
    sa.Column('industry', sa.String(length=32), nullable=True),
    sa.Column('market', sa.String(length=16), nullable=True),
    sa.Column('list_date', sa.String(length=8), nullable=True),
    sa.Column('list_status', sa.String(length=1), nullable=True),
    sa.Column('exchange', sa.String(length=8), nullable=True),
    sa.Column('curr_type', sa.String(length=8), nullable=True),
    sa.Column('is_hs', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('ts_code')
    )
    op.create_table('stock_daily',
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.String(length=8), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('pre_close', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('pct_chg', sa.Float(), nullable=True),
    sa.Column('vol', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('ts_code', 'trade_date')
    )
    op.create_table('trade_cal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('exchange', sa.String(length=8), nullable=True),
    sa.Column('cal_date', sa.String(length=8), nullable=False),
    sa.Column('is_open', sa.Integer(), nullable=True),
    sa.Column('pretrade_date', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_cal_cal_date'), 'trade_cal', ['cal_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_cal_cal_date'), table_name='trade_cal')
    op.drop_table('trade_cal')
    op.drop_table('stock_daily')
    op.drop_table('stock_basic')
    # ### end Alembic commands ###
